# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - WebApp-Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'components.json'
      - 'package.json'
      - 'bun.lock'
      - 'next.config.ts'
      - 'next-env.d.ts'
      - 'tsconfig.json'
      - 'postcss.config.mjs'
      - 'eslint.config.mjs'
      - '.github/workflows/main_webapp-frontend.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: bun install
        run: |
          bun install
          bun run build

      - name: Prepare artifact for deployment job
        run: |
          mkdir -p ./standalone
          cp -R ./.next/standalone ./
          cp -R ./public ./standalone/public
          cp -R ./.next/static ./standalone/.next
          rm -rf ./standalone/.env

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: node-app
          path: ./standalone

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WebApp-Frontend'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_339FE3A2663148258E1BEE0CA394AB85 }}